{
 "title": "eBPF Exporter Disk BIO",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Node",
    "query": "label_values(node_disk_read_time_seconds_total, instance)"
   },
   {
    "name": "device",
    "label": "Device",
    "query": "label_values(node_disk_read_time_seconds_total{instance=~\"$instance\"}, device)"
   }
  ]
 },
 "panels": [
  { "title": "Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "biolatency read",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"read\", instance=\"$instance\", device=\"$device\"}[$__interval]) or rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"read\", instance=\"$instance\", device=\"$device\"}[5m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "biolatency write",
   "type": "heatmap",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"write\", instance=\"$instance\", device=\"$device\"}[$__interval]) or rate(ebpf_exporter_bio_latency_seconds_bucket{operation=\"write\", instance=\"$instance\", device=\"$device\"}[5m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentiles and averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_bio_latency_seconds_bucket{instance=\"$instance\", device=\"$device\"}[$__interval]) )",
     "legendFormat": "90% {{ operation }}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_bio_latency_seconds_bucket{instance=\"$instance\", device=\"$device\"}[$__interval]) )",
     "legendFormat": "95% {{ operation }}"
    },
    {
     "expr": "rate(ebpf_exporter_bio_latency_seconds_sum{instance=\"$instance\", device=\"$device\"}[$__interval]) / rate(ebpf_exporter_bio_latency_seconds_count{instance=\"$instance\", device=\"$device\"}[$__interval])",
     "legendFormat": "{{ operation }} average"
    }
   ]
  },
  {
   "title": "\"Old\" Latencies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Latency Read",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(\n(rate(node_disk_read_time_seconds_total{device=~\"$device\", instance=\"$instance\"}[$__interval]) / \nrate(node_disk_reads_completed_total{device=~\"$device\", instance=\"$instance\"}[$__interval])) > 0 or \n(irate(node_disk_read_time_seconds_total{device=~\"$device\", instance=\"$instance\"}[5m]) / \nirate(node_disk_reads_completed_total{device=~\"$device\", instance=\"$instance\"}[5m])) > 0\n)",
       "legendFormat": "Read"
      }
     ]
    },
    {
     "title": "Disk Latency Write",
     "type": "graph",
     "description": "Shows average latency for Reads and Writes IO Devices.  Higher than typical latency for highly loaded storage indicates saturation (overload) and is frequent cause of performance problems.  Higher than normal latency also can indicate internal storage problems.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(\n(rate(node_disk_write_time_seconds_total{device=~\"$device\", instance=\"$instance\"}[$__interval]) / \nrate(node_disk_writes_completed_total{device=~\"$device\", instance=\"$instance\"}[$__interval])) > 0 or \n(irate(node_disk_write_time_seconds_total{device=~\"$device\", instance=\"$instance\"}[5m]) / \nirate(node_disk_writes_completed_total{device=~\"$device\", instance=\"$instance\"}[5m])) > 0\n)",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  },
  { "title": "IO Size", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "bio bytes read",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_bucket{instance=\"$instance\", device=\"$device\", operation=\"read\"}[$__interval]) or rate(ebpf_exporter_bio_size_bytes_bucket{instance=\"$instance\", device=\"$device\", operation=\"read\"}[5m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "bio bytes write",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_bucket{instance=\"$instance\", device=\"$device\", operation=\"write\"}[$__interval]) or rate(ebpf_exporter_bio_size_bytes_bucket{instance=\"$instance\", device=\"$device\", operation=\"write\"}[5m])",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Percentiles and averages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(ebpf_exporter_bio_size_bytes_bucket{instance=\"$instance\", device=\"$device\"}[$__interval]) )",
     "legendFormat": "90% {{ operation }}"
    },
    {
     "expr": "histogram_quantile(0.95, rate(ebpf_exporter_bio_size_bytes_bucket{instance=\"$instance\", device=\"$device\"}[$__interval]) )",
     "legendFormat": "95% {{ operation }}"
    },
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_sum{instance=\"$instance\", device=\"$device\"}[$__interval]) / rate(ebpf_exporter_bio_size_bytes_count{instance=\"$instance\", device=\"$device\"}[$__interval])",
     "legendFormat": "{{ operation }} average"
    }
   ]
  },
  {
   "title": "Total bytes read/written",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bio_size_bytes_sum{instance=\"$instance\", device=\"$device\"}[$__interval])",
     "legendFormat": "Sum {{ operation }}"
    }
   ]
  },
  {
   "title": "\"Old\" IO Size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IO Size Read",
     "type": "graph",
     "description": "Shows average size of a single disk operation.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(\n(rate(node_disk_read_bytes_total{instance=\"$instance\", device=~\"$device\"}[$__interval]) * 512 / \nrate(node_disk_reads_completed_total{instance=\"$instance\", device=~\"$device\"}[$__interval])) > 0 or \n(irate(node_disk_read_bytes_total{instance=\"$instance\", device=~\"$device\"}[5m]) * 512 / \nirate(node_disk_reads_completed_total{instance=\"$instance\", device=~\"$device\"}[5m])) > 0\n)",
       "legendFormat": "Read size"
      },
      { "calculatedInterval": "2m", "legendFormat": "Write size" }
     ]
    },
    {
     "title": "Disk IO Size Write",
     "type": "graph",
     "description": "Shows average size of a single disk operation.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "sum(\n(rate(node_disk_written_bytes_total{instance=\"$instance\", device=~\"$device\"}[$__interval]) * 512 / \nrate(node_disk_writes_completed_total{instance=\"$instance\", device=~\"$device\"}[$__interval])) > 0 or \n(irate(node_disk_written_bytes_total{instance=\"$instance\", device=~\"$device\"}[5m]) * 512 / \nirate(node_disk_writes_completed_total{instance=\"$instance\", device=~\"$device\"}[5m])) > 0\n) ",
       "legendFormat": "Write size"
      }
     ]
    }
   ]
  }
 ]
}