{
 "title": "IPC Stat",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "2s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "job",
    "query": "label_values(node_uname_info, job)"
   },
   {
    "name": "instance",
    "query": "label_values(node_uname_info{job=\"$job\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "IPC",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(node_perf_instructions_total{instance=\"$instance\"}[5s])/rate(node_perf_cpucycles_total{instance=\"$instance\"}[5s])"
    }
   ]
  },
  {
   "title": "CPU cycles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_perf_cpucycles_total[5s])"
    }
   ]
  },
  {
   "title": "CPU Instructions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_perf_instructions_total[5s])"
    },
    {}
   ]
  }
 ]
}